[project]
name = "ironpdf-python-license-keys"
version = "1.0.0"
description = "Code examples demonstrating IronPDF for Python Feature: License Keys"
license = { file = "LICENSE" }
readme = "README.md"
homepage = "https://github.com/iron-software/IronPdfPython.Examples"
keywords = ["IronPDF for Python", "python", "License Keys", "ironpdfpython.examples", "Getting Started"]
dependencies = ["ironpdf==2026.8.0.1"]