[project]
name = "ironpdf-python-digitally-sign-a-pdf"
version = "1.0.0"
description = "Code examples demonstrating IronPDF for Python Feature: Digitally Sign A Pdf"
license = { file = "LICENSE" }
readme = "README.md"
homepage = "https://github.com/iron-software/IronPdfPython.Examples"
keywords = ["IronPDF for Python", "python", "Digitally Sign A Pdf", "ironpdfpython.examples", "Code Example"]
dependencies = ["ironpdf==2026.8.0.1"]